# -*- coding: utf-8 -*-
"""Ponmathi_Steamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17VUvGINevR5G3IaIhAADmMOP6Lw_uM9y
"""

!pip install streamlit pyngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import re
# 
# st.title("🔐 Password Strength Detector")
# 
# password = st.text_input("Enter your password", type="password")
# 
# def check_strength(password):
#     score = 0
# 
#     if len(password) >= 8:
#         score += 1
#     if re.search(r"[A-Z]", password):
#         score += 1
#     if re.search(r"[a-z]", password):
#         score += 1
#     if re.search(r"[0-9]", password):
#         score += 1
#     if re.search(r"[!@#$%^&*(),.?\":{}|<>]", password):
#         score += 1
# 
#     return score
# 
# if password:
#     strength = check_strength(password)
# 
#     if strength <= 2:
#         st.error("❌ Weak Password")
#     elif strength == 3 or strength == 4:
#         st.warning("⚠️ Medium Password")
#     else:
#         st.success("✅ Strong Password")
# 
#     st.write("### Password Checklist")
#     st.write("✔️ At least 8 characters" if len(password) >= 8 else "❌ At least 8 characters")
#     st.write("✔️ Uppercase letter" if re.search(r"[A-Z]", password) else "❌ Uppercase letter")
#     st.write("✔️ Lowercase letter" if re.search(r"[a-z]", password) else "❌ Lowercase letter")
#     st.write("✔️ Number" if re.search(r"[0-9]", password) else "❌ Number")
#     st.write("✔️ Special character" if re.search(r"[!@#$%^&*(),.?\":{}|<>]", password) else "❌ Special character")

from pyngrok import ngrok

ngrok.set_auth_token("379rcGrm8FIyumBrHanVrb8gghF_Y4AVNqtMTd26vkSVMRMo")

!streamlit run app.py &>/content/logs.txt &

public_url = ngrok.connect(8501)
public_url