# -*- coding: utf-8 -*-
"""Ponmathi_streamlitcode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UBiKKIgak0FVMhTxEBogedTwjKey2le_
"""

import streamlit as st

st.set_page_config(
   page_title="Hi Chichu",
   layout="centered"
)

st.title("Hello Chichu")
st.subheader("Good Boy")
st.subheader("Sleep Baby🥱🥱")
